apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wp-practice
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2