version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11

  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region ap-south-2 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.ap-south-2.amazonaws.com
      - echo "Getting commit ID..."
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "Commit hash: $COMMIT_HASH"

  build:
    commands:
      - cd devops-java-ecr-project
      - mvn clean package -DskipTests
      - docker build -t java-spring-ecr-project:latest .
      - docker tag java-spring-ecr-project:latest $AWS_ACCOUNT_ID.dkr.ecr.ap-south-2.amazonaws.com/java-spring-ecr-project:$COMMIT_HASH

  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-south-2.amazonaws.com/java-spring-ecr-project:$COMMIT_HASH
      - printf '[{"name":"java-app","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.ap-south-2.amazonaws.com/java-spring-ecr-project:$COMMIT_HASH > imagedefinitions.json
      - aws ecs update-service --cluster java-ECR-project-dev-cluster --service java-ECR-project-dev-service --force-new-deployment --region ap-south-2

artifacts:
  files:
    - imagedefinitions.json