pipeline {
    agent any
    environment{
        AWS_REGION = 'ap-south-1'
        ECR_REPO = '911319296463.dkr.ecr.ap-south-1.amazonaws.com/varshita5233/ecr-eks-repo'
        CLUSTER_NAME = 'eks-terraform-project-demo-dev'
        IMAGE_TAG = "v1.${BUILD_NUMBER}"
    }
    stages {
        stage('Checkout') {
            steps{
                git branch: 'main', url: 'https://github.com/Varshita5233/Devops_Projects.git'
            }
        }
        stage('Build Docker Image'){
            steps{
                dir('eks-terraform-project/app'){
                    sh "docker build -t app:${IMAGE_TAG} ."
                }
            }
        }
        stage('Login to ECR'){
            steps{
                sh '''
                aws ecr get-login-password --region $AWS_REGION | \
                docker login --username AWS --password-stdin 911319296463.dkr.ecr.ap-south-1.amazonaws.com
                '''
            }
        }
        stage('Tag & push to ECR'){
            steps{
                sh """
                docker tag app:${IMAGE_TAG} ${ECR_REPO}:${IMAGE_TAG} 
                docker push ${ECR_REPO}:${IMAGE_TAG} 
                """
            }
        }
        stage('Update Deployment Image'){
            steps{
                sh """
                sed -i 's|IMAGE_PLACEHOLDER|${IMAGE_TAG}|g' eks-terraform-project/k8s/base/deployment.yaml
                """
            }
        }
        stage('Deploy to kubernetes'){
            steps{
                withKubeConfig([credentialsId: 'eks-kubeconfig', secretFile: true]) {
                sh """
                kubectl apply -f eks-terraform-project/k8s/base/namespace.yaml
                kubectl apply -f eks-terraform-project/k8s/base
                """
                }
            }
        }
        
    }
    post {
        success {
            echo "Deployed image: ${ECR_REPO}:${IMAGE_TAG}"
        }
        failure {
            echo "Pipeline failed — check logs above"
        }
    }
}