apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wp-practice
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:6.5-apache
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql.wp-practice.svc.cluster.local:3306
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: mysql-secret
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: mysql-secret
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: mysql-secret
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wp-practice
spec:
  selector:
    app: wordpress
  ports:
    - port: 80