replicaCount: 1

image:
  repository: ghcr.io/varshita5233/products-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8081

# Ingress - exposes the service via the NGINX ingress controller
ingress:
  enabled: true

# Environment variables injected into the container.
env:
  EUREKA_CLIENT_ENABLED: "false"
  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
  EUREKA_CLIENT_FETCH_REGISTRY: "false"
  AUTH_SERVER_ISSUER: "http://localhost:9000"

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi