apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: eks-node-app-hpa
  namespace: eks-node-app
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eks-node-app

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 # scale when cpu>70%

  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80  # Scale when memory > 80%