apiVersion: v2
name: backend
description: A demo web app's backend deployed to EKS
type: application
version: 1.0.0        # the chart's own version
appVersion: "1.0.0"  # the version of the app it deploys
