replicaCount: 2

image:
  repository: REPLACE_WITH_ECR/backend
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 50m           # REQUIRED for HPA to calculate against
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50

ingress:
  enabled: true
