{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-myapp
  labels:
    release: monitoring        # matches your kube-prometheus-stack release
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-myapp
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}