server:
  port: 8082

spring:
  application:
    name: order-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_ISSUER:http://localhost:9000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}



resilience4j:
  circuitbreaker:
    instances:
      product-service:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        record-exceptions:
          - feign.FeignException
          - java.io.IOException
        ignore-exceptions:
          - org.quickcart.orders.exception.ProductNotFoundException
          - org.quickcart.orders.exception.InsufficientStocksException
          - org.quickcart.orders.exception.OrderNotFoundException
          - org.quickcart.orders.exception.AlreadyCanceledOrderException


  retry:
    instances:
      product-service:
        maxAttempts: 2
        waitDuration: 500ms
        retryExceptions:
          - feign.FeignException$ServiceUnavailable
          - feign.RetryableException
        ignoreExceptions:
          - org.quickcart.orders.exception.ProductNotFoundException
          - org.quickcart.orders.exception.InsufficientStocksException
          - org.quickcart.orders.exception.OrderNotFoundException
          - org.quickcart.orders.exception.AlreadyCanceledOrderException





logging:
  level:
    io.github.resilience4j: DEBUG
