apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-order-service
  labels:
    app: {{ .Release.Name }}-order-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-order-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-order-service
    spec:
      containers:
        - name: order-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            # Tell Spring Boot to also load config from the mounted file.
            # "optional:" so it won't fail if the path is missing.
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "optional:file:/config/application.yml"
            - name: AUTH_SERVER_ISSUER
              value: "http://localhost:9000"
          volumeMounts:
            - name: config-volume
              mountPath: /config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-order-service-config
